version: '3.8'

services:
  api:
    build: .
    container_name: kindergarten_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.server.app:create_app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:15
    container_name: kindergarten_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: kindergarten_redis
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: kindergarten_celery
    command: celery -A app.core.celery worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - api
      - redis

  celery-beat:
    build: .
    container_name: kindergarten_celery_beat
    command: celery -A app.core.celery beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - api
      - redis

volumes:
  pgdata:
